/* Generated by CIL v. 1.7.0 */
/* print_CIL_Input is false */

struct t___0;
struct t___9;
struct t___23;
extern void signal(int sig , void *func ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
int o___7  =    0;
typedef struct t___0 o___8;
struct t___9 {
   int f___10 ;
   struct t___9 *f___11 ;
};
extern double strtod(char const   *str , char const   *endptr ) ;
extern int fclose(void *stream ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern void abort() ;
extern void exit(int status ) ;
extern int raise(int sig ) ;
extern int fprintf(struct t___0 *stream , char const   *format  , ...) ;
struct t___9 *o___12  =    (struct t___9 *)0;
extern int rand() ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
void o___13(unsigned long *l___690 ) ;
void o___14(unsigned long *l___692 ) ;
void o___15(unsigned long *l___694 , unsigned long *l___695 ) ;
void o___16(void) ;
void o___17(unsigned long *l___697 ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned long maxlen ) ;
void o___18(unsigned long *l___699 , unsigned long *l___700 ) ;
int o___19[30]  = 
  {      213,      103,      3,      423, 
        61,      5,      23,      131, 
        5,      463,      488,      7, 
        3,      222,      17,      8, 
        117,      61,      463,      656, 
        8,      388,      187,      23, 
        8,      558,      36,      393, 
        656};
extern int gettimeofday(struct t___23 *tv , void *tz  , ...) ;
extern int printf(char const   *format  , ...) ;
int main(int l___676 , char **l___677 ) ;
extern unsigned long strlen(char const   *s ) ;
struct t___9 *o___20  =    (struct t___9 *)0;
void o___21(void) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
typedef struct t___9 *o___22;
extern unsigned long strnlen(char const   *s , unsigned long maxlen ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned long size ) ;
struct t___23 {
   long f___24 ;
   long f___25 ;
};
extern void *malloc(unsigned long size ) ;
extern int scanf(char const   *format  , ...) ;
void o___14(unsigned long *l___692 ) 
{ 


  {
  if (o___19[((o___7 & 2147483647) % 10) * 3] % o___19[5] != o___19[2]) {
    *l___692 = 42;
  } else {
    *l___692 = 41;
  }
}
}
void o___18(unsigned long *l___699 , unsigned long *l___700 ) 
{ 
  unsigned long l___702[2] ;
  unsigned long l___703 ;
  char l___704 ;
  unsigned long l___705 ;

  {
  l___705 = 49;
  while (1) {
    switch (l___705) {
    case 49: ;
    o___17(& l___705);
    break;
    case 48: 
    l___702[0UL] = *(l___699 + 0UL) & 67929800UL;
    l___705 = 36;
    break;
    case 47: 
    l___702[0UL] = (*(l___699 + 0UL) & 67929800UL) + 3;
    l___705 = 31;
    break;
    case 45: ;
    o___15(& l___703, & l___705);
    break;
    case 43: ;
    o___14(& l___705);
    break;
    case 42: ;
    l___705 = 45;
    break;
    case 41: ;
    o___13(& l___705);
    break;
    case 39: ;
    if ((o___19[((o___7 & 2147483647) % 10) * 3 + 1] % o___19[11] != o___19[5]) > 4) {
      l___705 = 38;
    } else {
      l___705 = 37;
    }
    break;
    case 38: ;
    l___705 = 32;
    break;
    case 37: ;
    if (o___19[((o___7 & 2147483647) % 10) * 3 + 1] % o___19[11] != o___19[5]) {
      l___705 = 35;
    } else {
      l___705 = 45;
    }
    break;
    case 36: 
    l___702[1UL] = *(l___699 + 0UL) << ((((l___702[0UL] >> 7UL) >> 1UL) & 7UL) | 1UL);
    l___705 = 34;
    break;
    case 35: 
    __asm__  volatile   (".byte 0x48,0x52,0x28,0x48,0x39,0x57,0x28":);
    l___705 = 32;
    break;
    case 34: 
    l___703 = 0UL;
    l___705 = 45;
    break;
    case 32: 
    l___704 = (char)6;
    l___705 = 25;
    break;
    case 31: 
    l___702[1UL] = (*(l___699 + 0UL) << ((((l___702[0UL] >> 7UL) >> 1UL) & 7UL) | 1UL)) % 9;
    l___705 = 29;
    break;
    case 30: ;
    if (o___19[((o___7 & 2147483647) % 10) * 3 + 1] % o___19[11] != o___19[5]) {
      l___705 = 28;
    } else {
      l___705 = 27;
    }
    break;
    case 29: 
    l___703 = 0UL;
    l___705 = 45;
    break;
    case 28: 
    l___704 = *((char *)(& l___702[l___703]) + 5) + 10;
    l___705 = 18;
    break;
    case 27: ;
    if (o___19[((o___7 & 2147483647) % 10) * 3 + 1] % o___19[11] == o___19[5]) {
      l___705 = 26;
    } else {
      l___705 = 20;
    }
    break;
    case 26: ;
    if (o___19[((o___7 & 2147483647) % 10) * 3 + 1] % o___19[11] != o___19[5]) {
      l___705 = 24;
    } else {
      l___705 = 22;
    }
    break;
    case 25: 
    *((char *)(& l___702[l___703]) + 5) = (char)8;
    l___705 = 23;
    break;
    case 24: 
    o___21();
    l___705 = 19;
    break;
    case 23: 
    *((char *)(& l___702[l___703]) + 0) = l___704;
    l___705 = 21;
    break;
    case 22: ;
    l___705 = 19;
    break;
    case 21: 
    l___703 = 5UL;
    l___705 = 39;
    break;
    case 20: ;
    l___705 = 19;
    break;
    case 19: 
    l___704 = *((char *)(& l___702[l___703]) + 5);
    l___705 = 10;
    break;
    case 18: 
    *((char *)(& l___702[l___703]) + 5) = (char)2;
    l___705 = 16;
    break;
    case 17: 
    *(l___700 + 0UL) = ((l___702[0UL] >> (((l___702[1UL] >> 1UL) & 15UL) | 1UL)) | (l___702[0UL] << (64UL - (((l___702[1UL] >> 1UL) & 15UL) | 1UL)))) | 0xffffffffeab889afUL;
    l___705 = 15;
    break;
    case 16: 
    *((char *)(& l___702[l___703]) + 0) = l___704;
    l___705 = 14;
    break;
    case 15: ;
    if (o___19[((o___7 & 2147483647) % 10) * 3] % o___19[5] == o___19[2]) {
      l___705 = 13;
    } else {
      l___705 = 5;
    }
    break;
    case 14: 
    l___703 = l___703;
    l___705 = 45;
    break;
    case 13: ;
    if (o___19[((o___7 & 2147483647) % 10) * 3 + 1] % o___19[11] == o___19[5]) {
      l___705 = 12;
    } else {
      l___705 = 11;
    }
    break;
    case 12: ;
    return;
    break;
    case 11: ;
    if (o___19[((o___7 & 2147483647) % 10) * 3 + 1] % o___19[11] == o___19[5]) {
      l___705 = 9;
    } else {
      l___705 = 7;
    }
    break;
    case 10: 
    *((char *)(& l___702[l___703]) + 5) = *((char *)(& l___702[l___703]) + 0);
    l___705 = 8;
    break;
    case 9: ;
    return;
    break;
    case 8: 
    *((char *)(& l___702[l___703]) + 0) = l___704;
    l___705 = 6;
    break;
    case 7: ;
    return;
    break;
    case 6: 
    l___703 ++;
    l___705 = 45;
    break;
    case 5: ;
    if ((o___19[((o___7 & 2147483647) % 10) * 3 + 1] % o___19[11] == o___19[5]) == 6) {
      l___705 = 4;
    } else {
      l___705 = 1;
    }
    break;
    case 4: ;
    if ((o___19[((o___7 & 2147483647) % 10) * 3 + 1] % o___19[11] == o___19[5]) < 4) {
      l___705 = 3;
    } else {
      l___705 = 2;
    }
    break;
    case 3: ;
    return;
    break;
    case 2: ;
    return;
    break;
    case 1: ;
    return;
    break;
    }
  }
}
}
void o___16(void) 
{ 


  {

}
}
void o___13(unsigned long *l___690 ) 
{ 


  {
  if (o___20 != o___12) {
    *l___690 = 39;
  } else {
    *l___690 = 30;
  }
}
}
int main(int l___676 , char **l___677 ) 
{ 
  unsigned long l___679[1] ;
  unsigned long l___680[1] ;
  int l___681 ;
  unsigned long l___682 ;
  int l___683 ;
  int l___684 ;
  int l___685 ;
  struct t___9 *l___686 ;

  {
  o___16();
  l___684 = 0;
  while (l___684 < 2) {
    l___685 = rand();
    {
    l___686 = (struct t___9 *)malloc(16UL);
    if (l___686 != (struct t___9 *)0UL) {
      l___686->f___10 = l___685;
      if (o___20 != (struct t___9 *)0UL) {
        l___686->f___11 = o___20->f___11;
        o___20->f___11 = l___686;
      } else {
        l___686->f___11 = l___686;
        o___20 = l___686;
      }
    } else {

    }
    }
    l___684 ++;
  }
  o___12 = o___20;
  o___7 = (int )((unsigned long )l___677) - o___7;
  o___7 = l___676 >> o___7;
  o___21();
  if (l___676 != 2) {
    printf("Call this program with %i arguments\n", 1);
    exit(-1);
  }
  l___681 = 0;
  while (l___681 < 1) {
    l___682 = strtoul((char const   *)*(l___677 + (l___681 + 1)), (char const   *)0,
                      10);
    l___679[l___681] = l___682;
    l___681 ++;
  }
  o___7 = l___681 - o___7;
  o___7 = (int )l___682 & o___7;
  o___18((unsigned long *)(l___679), (unsigned long *)(l___680));
  l___683 = 0;
  while (l___683 < 1) {
    printf("%lu\n", l___680[l___683]);
    l___683 ++;
  }
  o___7 = l___683 - o___7;
  return (0);
}
}
void o___17(unsigned long *l___697 ) 
{ 


  {
  if (o___19[((o___7 & 2147483647) % 10) * 3] % o___19[5] == o___19[2]) {
    *l___697 = 48;
  } else {
    *l___697 = 47;
  }
}
}
void o___15(unsigned long *l___694 , unsigned long *l___695 ) 
{ 


  {
  if (*l___694 < 2UL) {
    *l___695 = 43;
  } else {
    *l___695 = 17;
  }
}
}
void o___21(void) 
{ 


  {
  return;
}
}
