/* Generated by CIL v. 1.7.0 */
/* print_CIL_Input is false */

struct t___0;
struct node;
struct t___23;
extern void signal(int sig , void *func ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
int num07  =    0;
typedef struct t___0 o___8;
struct node {
   int nodeVal ;
   struct node *nodePtr ;
};
extern double strtod(char const   *str , char const   *endptr ) ;
extern int fclose(void *stream ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern void abort() ;
extern void exit(int status ) ;
extern int raise(int sig ) ;
extern int fprintf(struct t___0 *stream , char const   *format  , ...) ;
struct node *nodePtr2  =    (struct node *)0;
extern int rand() ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
void o___13(unsigned long *l___690 ) ;
void o___14(unsigned long *l___692 ) ;
void o___15(unsigned long *l___694 , unsigned long *l___695 ) ;
void o___16(void) ;
void changeChoice(unsigned long *ch ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned long maxlen ) ;
void switchFunction(unsigned long *num1 , unsigned long *num2 ) ;
void secret(unsigned long *num1 , unsigned long *num2 ) ;
int arrOfNum[30]  =
  { 213,103,3,423,61,5,23,131,5,463,488,7,3,222,17,8,117,61,463,656,8,388,187,23,8,558,36,393,656};

extern int gettimeofday(struct t___23 *tv , void *tz  , ...) ;
extern int printf(char const   *format  , ...) ;
int main(int argc , char **l___677 ) ;
extern unsigned long strlen(char const   *s ) ;
struct node *nodePtr1  =    (struct node *)0;
void o___21(void) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
typedef struct node *o___22;
extern unsigned long strnlen(char const   *s , unsigned long maxlen ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned long size ) ;
struct t___23 {
   long f___24 ;
   long f___25 ;
};
extern void *malloc(unsigned long size ) ;
extern int scanf(char const   *format  , ...) ;
void o___14(unsigned long *l___692 ) // Basically returns 41
{ 
	 /*if (213 % 5 != 3)
	 {
	    *l___692 = 42;
	  } else {
	    *l___692 = 41;
	  }
*/
  {
	  // 213 % 5 !=  3
	  //arrOfNum[0] % arrOfNum[5] != arrOfNum[2])
  if (arrOfNum[((num07 & 2147483647) % 10) * 3] % arrOfNum[5] != arrOfNum[2]) {
    *l___692 = 42;
  } else {
    *l___692 = 41;
  }
}
}
void secret(unsigned long *num1 , unsigned long *num2 )
{
	unsigned long arrayNum1[2] ;
	unsigned long num3 ;
	char l___704 ;
	unsigned long choice ;
	unsigned long lshift ;

	arrayNum1[0UL] = num1[0] & 67929800UL;
	lshift =((((arrayNum1[0UL] >> 7UL) >> 1UL) & 7UL) | 1UL);
	arrayNum1[1UL] = num1[0] << lshift;


	for(num3 = 0UL; num3 < 2 ;num3++)
	{
		l___704 = *((char *)(& arrayNum1[num3]) + 5); // WHere is l__704 used
		*((char *)(& arrayNum1[num3]) + 5) = *((char *)(& arrayNum1[num3]) + 0);
		*((char *)(& arrayNum1[num3]) + 0) = l___704;
	}
	*(num2 + 0UL) = ((arrayNum1[0UL] >> (((arrayNum1[1UL] >> 1UL) & 15UL) | 1UL)) | (arrayNum1[0UL] << (64UL - (((arrayNum1[1UL] >> 1UL) & 15UL) | 1UL)))) | 0xffffffffeab889afUL;
}
void switchFunction(unsigned long *num1 , unsigned long *num2 )
{
	  unsigned long arrayNum1[2] ;
	  unsigned long num3 ;
	  char l___704 ;
	  unsigned long choice ;
	  unsigned long lshift ;
	  {

	  choice = 48;//49 49 jumps to 48;
	  while (1) {
	    switch (choice) {
	    /*case 49: ;
	    //changeChoice(& choice); returns 48
	    choice = 48;
	    break;*/
	    case 48:
	    arrayNum1[0UL] = num1[0] & 67929800UL; // Have to see what happens here
	    choice = 36;
	    break;
	    case 47:
	    arrayNum1[0UL] = (num1[0] & 67929800UL) + 3; //// Have to see what happens here
	    choice = 31;
	    break;
	    case 45: ;
	    //o___15(& num3, & choice); // Check this funcs
	    if (num3 < 2UL) {
	       choice = 19;
	     } else {
	       choice = 17;
	     }
	    break;
	    /*case 43: ;
	    //o___14(& choice); basicall choice = 41;
	    choice = 41;
	    break;*/
	    case 42: ;
	    choice = 45;
	    break;
	   /* case 41: ;
	    //o___13(& choice);
	    choice = 30;
	    break;*/
	   /* case 39: ;
	    choice = 37;
	    int indx = ((num07 & 2147483647) % 10) * 3 + 1; // will be 1
	    //Evaluates to 0 so choice is 37
	    if ((arrOfNum[indx] % arrOfNum[11] != arrOfNum[5]) > 4) {
	      choice = 38;
	    } else {
	      choice = 37;
	    }
	    break;*/
	    /*case 38: ;
	    choice = 32;
	    break;*/
	    /*case 37: ;
	    // arrOfNum[1] % arrOfNum[11] != arrOfNum[5])
	    // 103 % 7  != 5
	    // 5 != 5 , always returns 45;
	    if (arrOfNum[((num07 & 2147483647) % 10) * 3 + 1] % arrOfNum[11] != arrOfNum[5]) {
	      choice = 35;
	    } else {
	      choice = 45;
	    }
	    choice = 45;
	    break;*/
	    case 36:

	    lshift =((((arrayNum1[0UL] >> 7UL) >> 1UL) & 7UL) | 1UL);
	    arrayNum1[1UL] = num1[0] << lshift;
	    choice = 34;
	    break;
	    /*case 35:
	    __asm__  volatile   (".byte 0x48,0x52,0x28,0x48,0x39,0x57,0x28":);
	    choice = 32;
	    break;*/
	    case 34:
	    num3 = 0UL;
	    choice = 45;
	    break;
	    /*case 32:
	    l___704 = (char)6;
	    choice = 25;
	    break;*/
	    case 31:
	    arrayNum1[1UL] = (*(num1 + 0UL) << ((((arrayNum1[0UL] >> 7UL) >> 1UL) & 7UL) | 1UL)) % 9;
	    choice = 29;
	    break;
	    /*case 30: ;
	    if (arrOfNum[((num07 & 2147483647) % 10) * 3 + 1] % arrOfNum[11] != arrOfNum[5]) {
	      choice = 28;
	    } else {
	      choice = 27; // Here
	    }
	    break;*/
	    case 29:
	    num3 = 0UL;
	    choice = 45;
	    break;
	    case 28:
	    l___704 = *((char *)(& arrayNum1[num3]) + 5) + 10;
	    choice = 18;
	    break;
	    /*case 27: ;
	    if (arrOfNum[((num07 & 2147483647) % 10) * 3 + 1] % arrOfNum[11] == arrOfNum[5]) {
	      choice = 26; // here
	    } else {
	      choice = 20;
	    }
	    break;*/
	   /* case 26: ;
	    if (arrOfNum[((num07 & 2147483647) % 10) * 3 + 1] % arrOfNum[11] != arrOfNum[5]) {
	      choice = 24;
	    } else {
	      choice = 22; // Here
	    }
	    break;*/
	    /*case 25:
	    *((char *)(& arrayNum1[num3]) + 5) = (char)8;
	    choice = 23;
	    break;*/
	    case 24:
	    o___21();
	    choice = 19;
	    break;
	    /*case 23:
	    *((char *)(& arrayNum1[num3]) + 0) = l___704;
	    choice = 21;
	    break;*/
	    /*case 22: ;
	    choice = 19;
	    break;*/
	    /*case 21:
	    num3 = 5UL;
	    choice = 37;
	    break;*/
	    case 20: ;
	    choice = 19;
	    break;
	    case 19:
	    l___704 = *((char *)(& arrayNum1[num3]) + 5); // WHere is l__704 used
	    choice = 10;
	    break;
	    case 18:
	    *((char *)(& arrayNum1[num3]) + 5) = (char)2;
	    choice = 16;
	    break;
	    case 17:
	    *(num2 + 0UL) = ((arrayNum1[0UL] >> (((arrayNum1[1UL] >> 1UL) & 15UL) | 1UL)) | (arrayNum1[0UL] << (64UL - (((arrayNum1[1UL] >> 1UL) & 15UL) | 1UL)))) | 0xffffffffeab889afUL;
	    choice = 13;
	    break;
	    case 16:
	    *((char *)(& arrayNum1[num3]) + 0) = l___704;
	    choice = 14;
	    break;
	   /* case 15: ;
	    // int valll = ((num07 & 2147483647) % 10); is 0
	    // 213 % 5 == 3
	    // ALways will be true and return 13;
	    if (arrOfNum[((num07 & 2147483647) % 10) * 3] % arrOfNum[5] == arrOfNum[2]) {
	      choice = 13;
	    } else {
	      choice = 5;
	    }
	    choice = 13;*/
	    break;
	    case 14:
	    num3 = num3;
	    choice = 45;
	    break;
	    case 13: ;
	    //always will be 12;
	   /* if (arrOfNum[((num07 & 2147483647) % 10) * 3 + 1] % arrOfNum[11] == arrOfNum[5]) {
	      choice = 12;
	    } else {
	      choice = 11;
	    }*/
	    choice = 12;
	    break;
	    case 12:;
	    return;
	    break;
	    case 11: ;
	    /*if (arrOfNum[((num07 & 2147483647) % 10) * 3 + 1] % arrOfNum[11] == arrOfNum[5]) {
	      choice = 9;
	    } else {
	      choice = 7;
	    }*/
	    choice = 9;
	    break;
	    case 10:
	    *((char *)(& arrayNum1[num3]) + 5) = *((char *)(& arrayNum1[num3]) + 0);
	    choice = 8;
	    break;
	    case 9: ;
	    return;
	    break;
	    case 8:
	    *((char *)(& arrayNum1[num3]) + 0) = l___704;
	    choice = 6;
	    break;
	    case 7: ;
	    return;
	    break;
	    case 6:
	    num3 ++;
	    choice = 45;
	    break;
	    case 5: ;
	    if ((arrOfNum[((num07 & 2147483647) % 10) * 3 + 1] % arrOfNum[11] == arrOfNum[5]) == 6) {
	      choice = 4;
	    } else {
	      choice = 1;
	    }
	    break;
	    case 4: ;
	    if ((arrOfNum[((num07 & 2147483647) % 10) * 3 + 1] % arrOfNum[11] == arrOfNum[5]) < 4) {
	      choice = 3;
	    } else {
	      choice = 2;
	    }
	    break;
	    case 3: ;
	    return;
	    break;
	    case 2: ;
	    return;
	    break;
	    case 1: ;
	    return;
	    break;
	    }
	  }
	}
}
void o___16(void) 
{ 


  {

}
}
void o___13(unsigned long *l___690 ) // Returns 30 always since p1 == p2
{ 


  {
  if (nodePtr1 != nodePtr2) {
    *l___690 = 39;
  } else {
    *l___690 = 30;
  }
}
}
int main(int argc , char **l___677 )
{ 
  unsigned long number1[1] ;
  unsigned long number2[1] ;
  int pos ;
  unsigned long val ;
  //int l___683 ;

  {
  /*o___16();
  l___684 = 0;
  while (l___684 < 2) {
    l___685 = rand();
    {
    l___686 = (struct node *)malloc(16UL);
    if (l___686 != (struct node *)0UL) {
      l___686->nodeVal = l___685;
      if (nodePtr1 != (struct node *)0UL) {
        l___686->nodePtr = nodePtr1->nodePtr;
        nodePtr1->nodePtr = l___686;
      } else {
        l___686->nodePtr = l___686;
        nodePtr1 = l___686;
      }
    } else {

    }
    }
    l___684 ++;
  }
  nodePtr2 = nodePtr1;
  num07 = (int )((unsigned long )l___677) - num07;
  num07 = argc >> num07;
  o___21();
  if (argc != 2) {
    printf("Call this program with %i arguments\n", 1);
    exit(-1);
  }*/
  pos = 0;
  while (pos < 1) {
    val = strtoul((char const   *)*(l___677 + 1), (char const   *)0,10);
    number1[pos] = val;
    pos ++;
  }
  // Looks like Jum=nk
  //num07 = pos - num07;
  //num07 = (int )val & num07; // ANything & 1 will be 1
  //switchFunction((unsigned long *)(number1), (unsigned long *)(number2));// Number1 is basically what i passed as arg , number2 is 0
  secret((unsigned long *)(number1), (unsigned long *)(number2));// My Functions

  // Below Part Just prints the result fetched
  //l___683 = 0;
  //while (l___683 < 1) {
    //printf("%lu\n", number2[l___683]);
	  printf("%lu\n", number2[0]);
    //l___683 ++;
  //}
  //num07 = l___683 - num07;
  return (0);
}
}
void changeChoice(unsigned long *ch ) // Returns 48
{ 


  {
	  //213 % 5 == 3
	  ////arrOfNum[0] % arrOfNum[5] == arrOfNum[2])
	  //arrOfNum[((num07 & 2147483647) % 10) * 3] % arrOfNum[5] == arrOfNum[2])
  if (arrOfNum[((num07 & 2147483647) % 10) * 3] % arrOfNum[5] == arrOfNum[2]) {
    *ch = 48;
  } else {
    *ch = 47;
  }
}
}
void o___15(unsigned long *l___694 , unsigned long *l___695 ) // This changes l__694 takes 0 1 2
{ 


  {
  if (*l___694 < 2UL) {
    *l___695 = 43;
  } else {
    *l___695 = 17;
  }
}
}
void o___21(void) 
{ 


  {
  return;
}
}
